server:
  port: 8080
spring:
  application:
    name: football-places-booking-system

  # configuration for java mail server
  mail:
    host: smtp.gmail.com  #Simple Mail Transfer Protocol
    # Port 587 is the standard port for secure SMTP (Simple Mail Transfer Protocol) communication.
    # It is used for sending email messages securely using STARTTLS or TLS encryption.
    port: 587
    username: football.booking.system@gmail.com
    password: wyetyvnywgyhrkzn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/footballPlayer
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Liquibase Configuration
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml


app:
  security:
    jwt:
      secret-key: tzyUDpPD0UdhgKyr0oTRNOL1hGajLHikkatdo29yrGvqfvLm10FcFEvNqT0PNEw1x/MyHN2GJFemFuzoSsRt/w==
      expiration: 86400000 # 1 day in milliseconds
